# Generated by Django 4.0.1 on 2022-01-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('free', 'مجانی'), ('payable', 'پرداختی')], default='free', max_length=24)),
            ],
        ),
    ]
